### ISSUE TITLE
On Journey column, the spelling is misspelled

### ISSUE THREAD

**Issue by Nawaz027** [guymenahem/the-kubernetes-journey#4]
On the Journey column, "The Jounrey" is written instead of "The Journey".

**Comment by Nawaz027** [comment]
I want to work on this issue.

**Comment by HeyAdityaPatidar** [comment]
Is anyone working on this issue?
I want to contribute on this issue.

**Comment by guymenahem** [comment]
Done by @HeyAdityaPatidar
